service: infracreation
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: ap-south-1
  deploymentPrefix: infracreation

resources:
  - ${file(./resources/ec2.yml)}
