---
Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Email
      Type: String
      Value: sudheer@gmail.com
      Description: SSM Parameter for running date command.

  BasicParameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: phoneNumber
      Type: String
      Value: 08888888888
      Description: SSM Parameter for running date command.

  BasicParameter2:
    Type: AWS::SSM::Parameter
    Properties:
      Name: universityName
      Type: String
      Value: illinois university
      Description: SSM Parameter for running date command.

  NewVolume:
    Type: AWS::EC2::Volume
  Properties: 
    Size: 1
    VolumeType: io1
    Iops: 100
    AvailabilityZone: !GetAtt Ec2Instance.AvailabilityZone
      
